gcp_credentials: ENCRYPTED[0d68e33902f5a9ced6118c84fc6bf50178366b0806ea033cf622099dbb33e7e2c8353900d0f099b31faa3f53e25bf21b]

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1910-eoan-v20191022
  zone: us-west2-a
  cpu: 2
  memory: 4GB
  disk: 20

task:
  env:
    DEPENDENCIES: bc gcc-multilib libssl-dev llvm-dev
                  libnuma-dev python3-sphinx libelf-dev selinux-policy-dev
                  libunbound-dev libunwind-dev python3-pip libelf-dev
                  autoconf automake libtool
                  libcap-ng-dev libssl-dev python3-dev
    COMPILER: gcc

  prepare_script:
    - cat /etc/lsb-release
    - sudo apt-get update 
    - sudo apt-get install -y ${DEPENDENCIES}
    - sudo apt-get install -y linux-source-5.3.0
    - cd /usr/src/linux-source-5.3.0; sudo bunzip2 linux-source-5.3.0.tar.bz2;sudo tar xvf linux-source-5.3.0.tar
    - cd /usr/src/linux-source-5.3.0/linux-source-5.3.0/; sudo make headers_install INSTALL_HDR_PATH=/usr
    - cd /usr/src/linux-source-5.3.0/linux-source-5.3.0/tools/lib/bpf; sudo make install; sudo make install_headers;
    - sudo touch /etc/ld.so.conf.d/libbpf.conf; sudo chmod a+w /etc/ld.so.conf.d/libbpf.conf;
    - sudo echo "/usr/local/lib64/" >> /etc/ld.so.conf.d/libbpf.conf; sudo ldconfig
    - ldconfig -p | grep libbpf
    - pip3 install --disable-pip-version-check --user six flake8 hacking
    - pip3 install --user --upgrade docutils


  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall" \
                  --enable-Werror --enable-afxdp
    - make -j2
    - sudo make check-afxdp 
