

gcp_credentials: ENCRYPTED[3d11b332216bbaa5cfb20219d2e2127c5d8b6d4448f8c87cf904696ae508413c70e3ea8c193583cf7d271812edc0b02c] 

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1904-disco-v20190417 
  zone: us-west2-a
  cpu: 2
  memory: 4GB
  disk: 20

task:
  env:
    DEPENDENCIES: bc gcc-multilib libssl-dev llvm-dev libjemalloc1 libjemalloc-dev \
                  libnuma-dev python3-sphinx libelf-dev selinux-policy-dev \
                  libunbound-dev libunbound-dev:i386 libunwind-dev python3-pip
    COMPILER: gcc

  prepare_script:
    - sudo apt-get install -y ${DEPENDENCIES}
    - pip install --disable-pip-version-check --user six flake8 hacking
    - pip install --user --upgrade docutils

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall" \
                  --enable-Werror --enable-afxdp
