

gcp_credentials: ENCRYPTED[547d86a94ee80027a454514b8219eae31cde752c4ba83ae642146ceef8305a8d03df9411a42beda134b4b9b901497b64]

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1904-disco-v20190417 
  zone: us-west2-a
  cpu: 2
  memory: 4GB
  disk: 20

task:
  env:
    DEPENDENCIES: bc gcc-multilib libssl-dev llvm-dev libjemalloc1 libjemalloc-dev \
                  libnuma-dev python3-sphinx libelf-dev selinux-policy-dev \
                  libunbound-dev libunbound-dev:i386 libunwind-dev python3-pip
    COMPILER: gcc

  prepare_script:
    - cat /etc/lsb-release
    - cat /etc/lsb-release
    - sudo apt-get install -y ${DEPENDENCIES}
    - pip install --disable-pip-version-check --user six flake8 hacking
    - pip install --user --upgrade docutils

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall" \
                  --enable-Werror --enable-afxdp
