gcp_credentials: ENCRYPTED[0d68e33902f5a9ced6118c84fc6bf50178366b0806ea033cf622099dbb33e7e2c8353900d0f099b31faa3f53e25bf21b]

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1910-eoan-v20191022
  zone: us-west2-a
  cpu: 2
  memory: 4GB
  disk: 20

task:
  env:
    DEPENDENCIES: bc gcc-multilib libssl-dev llvm-dev
                  libnuma-dev python3-sphinx libelf-dev selinux-policy-dev
                  libunbound-dev libunwind-dev python3-pip
    COMPILER: gcc

  prepare_script:
    - cat /etc/lsb-release
    - cat /etc/lsb-release
    - sudo apt-get install -y ${DEPENDENCIES}
    - pip install --disable-pip-version-check --user six flake8 hacking
    - pip install --user --upgrade docutils

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall" \
                  --enable-Werror --enable-afxdp
