

gcp_credentials: ENCRYPTED[aa6d813a32478438735d99897709d6851dc57c49]

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1904-disco-v20190417
  zone: us-central1-a
  cpu: 2
  memory: 40GB
  disk: 20

task:
  env:
    DEPENDENCIES: automake libtool gmake gcc wget openssl \
                  python3 py36-six py36-openssl py36-sphinx
    matrix:
      - COMPILER: gcc
      - COMPILER: clang

  prepare_script:
    - sysctl -w kern.coredump=0
    - pkg install -y ${DEPENDENCIES}

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall" \
                  MAKE=gmake --enable-Werror
