language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - valgrind

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96


script:
  - valgrind --help 
  - valgrind --log-file=$(pwd)/valgrind.%p --leak-check=full ls 
  - find . -name "valgrind.*"
  - ./boot.sh && ./configure && make
  - make check-valgrind TESTSUITEFLAGS='1102' 
  - ls /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/
  - ls /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/1102/
  - find . -name "valgrind.*" 
  - find /home/travis/build/williamtu/ovs-travis/ -name "valgrind.*"

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
