language: c
compiler:
  - gcc

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev

before_install: ./.travis/prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - TESTSUITE=1 KERNEL=3.18.1

script:
  - ./boot.sh && ./configure && make
  - make check TESTSUITEFLAGS='1000-1100'
  - make check-valgrind TESTSUITEFLAGS='1000-1100' 
  - grep -r "definitely lost" tests/testsuite.dir/
notifications:
  email:
    recipients:
      - u9012063@gmail.com 
