language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96


script:
  - ./boot.sh && ./configure && make
  - make check TESTSUITEFLAGS='1100'
  - make check-valgrind TESTSUITEFLAGS='1100' 
  - grep -r "definitely lost" tests/testsuite.dir/

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
