language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: 
    - ./boot.sh
    - ./configure 
    - make check TESTSUITEFLAGS='100'

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
