language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - valgrind

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96


script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
