language: c
compiler:
  - gcc
  - clang

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - valgrind

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - TESTSUITE=1 KERNEL=3.18.1
  - TESTSUITE=1 TESTVALGRIND=1 KERNEL=3.10.96

matrix:
  include:
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
