language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - valgrind
      - valgrind-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96


script:
  - valgrind --log-file=./valgrind.%p --leak-check=full --errors-for-leak-kinds=definite ls
  - ls valgrind*
  - cat ./valgrind.*
  - ./boot.sh && ./configure && make
  - make check-valgrind TESTSUITEFLAGS='1100' 
  - ls  /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/
  - ls  /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/1100/
  - grep -r "definitely lost" tests/testsuite.dir/

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
