language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - llvm-dev

before_install: ./.travis/prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - OPTS="--disable-ssl"
  - TESTSUITE=1 KERNEL=3.18.1
  - TESTSUITE=1 OPTS="--enable-shared"
  - BUILD_ENV="-m32" OPTS="--disable-ssl"
  - KERNEL=4.3.5

script:
  - ./boot.sh && ./configure && make
  - make check
  - make check-valgrind TESTSUITEFLAGS='1000-1500' 
notifications:
  email:
    recipients:
      - u9012063@gmail.com 
