language: c
compiler:
  - gcc

os:
  - linux

addons:
  apt:
    packages:
      - bc
      - gcc-multilib
      - libssl-dev
      - valgrind

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

sudo: false

env:
  - KERNEL=3.10.96


script:
  - valgrind --help | grep leak
  - valgrind --help 
  - mkdir -p /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/aaa 
  - valgrind --log-file=/home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/aaa/valgrind.%p --leak-check=full ls 
  - find . -name "valgrind.*"
  - ls /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/aaa/ 
  - ls valgrind*
  - cat ./valgrind.*
#  - ./boot.sh && ./configure && make
#  - make check-valgrind TESTSUITEFLAGS='1100' 
#  - ls /home/travis/build/williamtu/ovs-travis/tests/testsuite.dir/
#  - find . -name "valgrind.*" 
#  - find /home/travis/build/williamtu/ovs-travis/ -name "valgrind.*"
#  - grep -r "definitely lost" tests/testsuite.dir/

notifications:
  email:
    recipients:
      - u9012063@gmail.com 
